### ISSUE TITLE
out of bounds for time coordinates

### ISSUE THREAD

**Issue by zoezz96** [cerfacs-globc/icclim#67] opened 2021-03-24 06:55 UTC
![image](https://user-images.githubusercontent.com/49753029/112267799-f5266900-8cb0-11eb-903e-c838b98349a2.png)

**Comment by pagecp** [comment] 2021-03-29 07:38
Please try the latest icclim commit. It was a very complicated bug to fix... It was due to the implementation of non-standard calendar year types for the percentile calculations. The implementation was partial and it is why it was not always working.
I leave the issue open until you confirm that it works on your side.

**Comment by pagecp** [comment] 2021-03-29 07:40
Duplicate of #65

**Comment by bzah** [comment] 2022-01-10 14:15
Closing this.
icclim 5.0.0 is a complete rewrite of icclim, this bug will not be reproducible as is.

**Closed by bzah** 2022-01-10 14:15 UTC
